# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  image: pandoc/core:latest
  script:
    - pandoc -t html -s 解题报告.md -f markdown -o index.html -M title="PAT甲级解题报告" -H .public/custom.html --template=.public/template.html
    - rm -rf .public/*
    - cp index.html .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - pages
